name = "progrit-study-log-worker"
main = "worker/index.ts"
compatibility_date = "2024-09-10"
workers_dev = true

[[kv_namespaces]]
binding = "PROGRIT_KV"
id = "b9911ef74511411ba5c72b1071fcee9e"
preview_id = "07e9e6b734ac47db86425a016ea13cfa"
